Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network :public_network,:bridge=>"enp0s8"
  config.vm.network "private_network", ip: "192.168.1.45"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ipnoticsVM-modificar"
  end
end